Repository DuplosFidibuss/academic-time-planner, pull requests merged in 2022-12, with the labels that each got.

#113 Bugfix nullpointer
  AcademicTimePlanner/Pages/Index.razor.cs
Labels: bug

#115 Update PlanProjects.razor
  AcademicTimePlanner/Pages/PlanProjects.razor
Labels: frontend

#114 Documentation/ferbemar/describe unit tests
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner/Data/DataManager.cs
  doc/parts/methods.tex
Labels: documentation

#117 Feature/jansluk/98 link toggl and plan projects
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner.sln
  AcademicTimePlanner/Data/ChartData.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Data/DisplayData.cs
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/ProjectLinker.razor
  AcademicTimePlanner/Pages/ProjectLinker.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Shared/NavMenu.razor
  AcademicTimePlanner/Store/State/Charts/ChartsState.cs
  AcademicTimePlanner/Store/State/Charts/Effects.cs
  AcademicTimePlanner/Store/State/Charts/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/Effects.cs
  AcademicTimePlanner/Store/State/ProjectLinker/FetchChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/ProjectLinkerState.cs
  AcademicTimePlanner/Store/State/ProjectLinker/ProjectSelector.cs
  AcademicTimePlanner/Store/State/ProjectLinker/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SaveProjectsDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SwitchLinkingStepAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/TaskSelector.cs
Labels: enhancement, frontend, backend

#123 Update README.md
  README.md
Labels: documentation

#120 Update AcademicTimePlanner.csproj
  AcademicTimePlanner/AcademicTimePlanner.csproj
Labels: refactoring

#122 Documentation/jansluk/status display
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Data/TogglLoadOverviewData.cs
  AcademicTimePlanner/Pages/Toggl.razor
  doc/doc.bib
  doc/img/Linking_1.png
  doc/img/Linking_2.png
  doc/img/Linking_tasks1.png
  doc/img/Linking_tasks2.png
  doc/img/Toggl_associated.png
  doc/img/Toggl_deleted.png
  doc/img/Toggl_init.png
  doc/img/Toggl_loaded.png
  doc/img/Toggl_noProject.png
  doc/img/Toggl_validation.png
  doc/parts/fundamentals.tex
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation, frontend

#124 Documentation/jansluk/chapter 5
  doc/doc.bib
  doc/doc.tex
  doc/parts/discussion_prospects.tex
  doc/parts/fundamentals.tex
  doc/parts/introduction.tex
  doc/ressources/SoE-INIT_Bachelor-Titelblatt-Vorlage.doc
  doc/ressources/appendix.pdf
  doc/ressources/titlepage.pdf
Labels: documentation

#125 Cropped and resized pictures
  doc/img/CreateRepetitionOrEntry.PNG
  doc/img/Linking_1.png
  doc/img/Linking_2.png
  doc/img/Linking_tasks1.png
  doc/img/Linking_tasks2.png
  doc/img/Toggl_associated.png
  doc/img/Toggl_deleted.png
  doc/img/Toggl_init.png
  doc/img/Toggl_loaded.png
  doc/img/Toggl_noProject.png
  doc/img/Toggl_validation.png
  doc/parts/results.tex
Labels: documentation

#127 Bugfix/jansluk/experiments and bughunting
  AcademicTimePlanner/Data/DisplayData.cs
  doc/doc.tex
  doc/img/Linking_TogglNotFound.png
  doc/ressources/Erklaerung_BA.pdf
  doc/ressources/Erklaerung_BA_digital-_EN.doc
  doc/ressources/Erklaerung_PA.pdf
Labels: bug

#126 Update DataManager.cs
  AcademicTimePlanner/Data/DataManager.cs
Labels: refactoring

#128 Feature/jansluk/edit plan projects
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Pages/PlanProjects.razor
  AcademicTimePlanner/Pages/PlanProjects.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Store/State/ProjectFiles/DownloadPlanProjectAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/GetPlanProjectForDownloadAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/PlanProjectDownloader.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
Labels: enhancement, frontend

#129 Documentation/ferbemar/create edit planproject
  doc/img/CreatePlanEntry.PNG
  doc/img/CreatePlanEntry_List.PNG
  doc/img/CreatePlanProject.PNG
  doc/img/CreatePlanProjectButton.PNG
  doc/img/CreateRepetitionEntry.PNG
  doc/img/CreateRepetitionOrEntry.PNG
  doc/img/DownloadButton.PNG
  doc/img/EditButton.png
  doc/img/ImportButton.PNG
  doc/img/Index.PNG
  doc/img/IndexUnloaded.PNG
  doc/img/LoadedPlanProjectsList.PNG
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation

#130 Documentation/jansluk/28 draw class diagram
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanEntry.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanProject.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanTask.cs
  AcademicTimePlanner/ApplicationData/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/ApplicationData/Toggl/TogglProject.cs
  AcademicTimePlanner/DataManagement/DataManager.cs
  AcademicTimePlanner/DataManagement/TestTogglProject.cs
  AcademicTimePlanner/DisplayData/ProjectsData.cs
  AcademicTimePlanner/DisplayData/TogglLoadOverviewData.cs
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/JSONHandling/NewtonsoftJsonSerializer.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/PlanProjects.razor.cs
  AcademicTimePlanner/Pages/ProjectLinker.razor
  AcademicTimePlanner/Pages/ProjectLinker.razor.cs
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Program.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Services/TogglService/ITogglService.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
  AcademicTimePlanner/Store/State/Charts/ChartsState.cs
  AcademicTimePlanner/Store/State/Charts/Effects.cs
  AcademicTimePlanner/Store/State/Charts/Reducers.cs
  AcademicTimePlanner/Store/State/Charts/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/CreatePlanTaskAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/FinishPlanProjectCreationAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SwitchCreationStepAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/Effects.cs
  AcademicTimePlanner/Store/State/ProjectLinker/ProjectLinkerState.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SaveProjectsDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SwitchLinkingStepAction.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/SaveTogglSettingsAction.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
  AcademicTimePlanner/UIModels/DateFilter.cs
  AcademicTimePlanner/UIModels/ProjectSelector.cs
  AcademicTimePlanner/UIModels/TaskSelector.cs
  AcademicTimePlanner/UIModels/TogglSettings.cs
  doc/img/Architecture_overview.png
  doc/img/Architecture_overview.svg
  doc/img/classdiagram_prototype_current.PNG
  doc/parts/results.tex
Labels: documentation

#131 Update classdiagram_prototype_current.PNG
  doc/img/classdiagram_prototype_current.PNG
Labels: documentation

#132 Documentation/jansluk/103 general code review
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/TestTogglProject.cs
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanEntry.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanProject.cs
  AcademicTimePlanner/ApplicationData/Plan/PlanTask.cs
  AcademicTimePlanner/ApplicationData/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/ApplicationData/Toggl/TogglProject.cs
  AcademicTimePlanner/DataManagement/DataManager.cs
  AcademicTimePlanner/DisplayData/ProjectsData.cs
  AcademicTimePlanner/DisplayData/TogglLoadOverviewData.cs
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/JSONHandling/NewtonsoftJsonSerializer.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/PlanProjects.razor
  AcademicTimePlanner/Pages/PlanProjects.razor.cs
  AcademicTimePlanner/Pages/ProjectLinker.razor
  AcademicTimePlanner/Pages/ProjectLinker.razor.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/ITogglApiService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglDetailResponse.cs
  AcademicTimePlanner/Services/TogglApiService/TogglDetailResponseData.cs
  AcademicTimePlanner/Services/TogglService/ITogglService.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
  AcademicTimePlanner/Shared/NavMenu.razor
  AcademicTimePlanner/Shared/NavMenu.razor.cs
  AcademicTimePlanner/Shared/Wrapper.razor
  AcademicTimePlanner/Shared/Wrapper.razor.cs
  AcademicTimePlanner/Store/State/Charts/Effects.cs
  AcademicTimePlanner/Store/State/Charts/FetchChartDataAction.cs
  AcademicTimePlanner/Store/State/Charts/FilterChartDataAction.cs
  AcademicTimePlanner/Store/State/Charts/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/Effects.cs
  AcademicTimePlanner/Store/State/ProjectLinker/FetchChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/FetchTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
  AcademicTimePlanner/Store/State/Wrapper/Reducers.cs
  AcademicTimePlanner/Store/State/Wrapper/SetTitleAction.cs
  AcademicTimePlanner/Store/State/Wrapper/WrapperState.cs
  AcademicTimePlanner/UIModels/DateFilter.cs
  AcademicTimePlanner/UIModels/ProjectSelector.cs
  AcademicTimePlanner/UIModels/TaskSelector.cs
Labels: documentation

#133 Dokumentation/ferbemar/rework with corrections from uk
  README.md
  doc/img/ProjectOverview.PNG
  doc/img/ProjectOverview_FinishedProject.png
  doc/parts/discussion_prospects.tex
  doc/parts/fundamentals.tex
  doc/parts/introduction.tex
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation

#134 Documentation/jansluk/create data package
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/TestTogglProject.cs
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/Data/ApplicationData/Plan/PlanEntry.cs
  AcademicTimePlanner/Data/ApplicationData/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/Data/ApplicationData/Plan/PlanProject.cs
  AcademicTimePlanner/Data/ApplicationData/Plan/PlanTask.cs
  AcademicTimePlanner/Data/ApplicationData/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/Data/ApplicationData/Toggl/TogglProject.cs
  AcademicTimePlanner/Data/DisplayData/ProjectsData.cs
  AcademicTimePlanner/Data/DisplayData/TogglLoadOverviewData.cs
  AcademicTimePlanner/Data/MetaData/TogglCredentials.cs
  AcademicTimePlanner/DataManagement/DataManager.cs
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/PlanProjects.razor.cs
  AcademicTimePlanner/Pages/ProjectLinker.razor
  AcademicTimePlanner/Pages/ProjectLinker.razor.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Services/TogglService/ITogglService.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
  AcademicTimePlanner/Store/State/Charts/ChartsState.cs
  AcademicTimePlanner/Store/State/Charts/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/CreatePlanTaskAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/FinishPlanProjectCreationAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SwitchCreationStepAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/ProjectLinkerState.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SaveProjectsDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SetChartDataAction.cs
  AcademicTimePlanner/Store/State/ProjectLinker/SwitchLinkingStepAction.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/SaveTogglCredentialsAction.cs
  AcademicTimePlanner/Store/State/Toggl/SaveTogglSettingsAction.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
  doc/img/Architecture_overview.png
  doc/img/Architecture_overview.svg
  doc/parts/results.tex
Labels: documentation

#135 resize figures
  doc/img/blazorise-charts.png
  doc/img/figure1_prototype_charts.png
  doc/img/plotly-charts.png
  doc/img/radzen-charts.png
  doc/parts/methods.tex
Labels: documentation

#136 Include timeline
  doc/img/TimelineATP.png
  doc/parts/discussion_prospects.tex
  doc/parts/methods.tex
  doc/ressources/TimeLine_ATP.xlsx
Labels: documentation

#137 Documentation/jansluk/finish documentation
  README.md
  doc/doc.tex
  doc/parts/abstract.tex
  doc/parts/discussion_prospects.tex
  doc/parts/methods.tex
  doc/parts/results.tex
  doc/parts/vorwort.tex
  doc/ressources/Erklaerung_BA_digital-_EN.doc
  doc/ressources/Erklaerung_PA.pdf
  doc/ressources/README.pdf
  doc/ressources/SoE-INIT_Bachelor-Titelblatt-Vorlage.doc
  doc/ressources/appendix.pdf
  doc/ressources/titlepage.pdf
Labels: documentation

#138 Update readme.
  README.md
  doc/ressources/README.pdf
Labels: documentation
