Repository DuplosFidibuss/academic-time-planner, pull requests merged in 2022-11, with the labels that each got.

#59 Reafactoring/ferbemar/update test toggl project
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/JSON_Files/PlanProject.json
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/TimeSpan.cs
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/LoadPlanProjectsAction.cs
Labels: enhancement, backend, refactoring

#60 Refactoring/jansluk/51 replace bootstrap mask by entryform
  AcademicTimePlanner/Data/TogglSettings.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Program.cs
  AcademicTimePlanner/Services/BootstrapModalService/BootstrapModalService.cs
  AcademicTimePlanner/Services/BootstrapModalService/IBootstrapModalService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Shared/Editor.razor
  AcademicTimePlanner/Shared/Editor.razor.cs
  AcademicTimePlanner/Shared/NavMenu.razor
  AcademicTimePlanner/Store/Middleware/Persistence/Effects.cs
  AcademicTimePlanner/Store/Middleware/Persistence/PersistStateAction.cs
  AcademicTimePlanner/Store/Middleware/Persistence/PersistenceMiddleware.cs
  AcademicTimePlanner/Store/Middleware/Setup/SetupMiddleware.cs
  AcademicTimePlanner/Store/State/Editor/EditorAskForTogglCredentialsAction.cs
  AcademicTimePlanner/Store/State/Editor/EditorState.cs
  AcademicTimePlanner/Store/State/Editor/Effects.cs
  AcademicTimePlanner/Store/State/Editor/Field.cs
  AcademicTimePlanner/Store/State/Editor/Reducers.cs
  AcademicTimePlanner/Store/State/Editor/SaveEditorAction.cs
  AcademicTimePlanner/Store/State/Editor/ShowEditorAction.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/SaveTogglSettingsAction.cs
  AcademicTimePlanner/Store/State/TogglSettings/Effects.cs
  AcademicTimePlanner/Store/State/TogglSettings/Reducers.cs
  AcademicTimePlanner/Store/State/TogglSettings/SetTogglSettingsAction.cs
  AcademicTimePlanner/Store/State/TogglSettings/SetTogglSettingsStateAction.cs
  AcademicTimePlanner/Store/State/TogglSettings/TogglSettingsState.cs
  AcademicTimePlanner/wwwroot/index.html
  AcademicTimePlanner/wwwroot/scripts/bootstrap-modal-helpers.js
Labels: frontend, refactoring

#61 Frontend/jansluk/27 create synchronize button
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Store/State/Toggl/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
Labels: enhancement, frontend

#62 Frontend/ferbemar/54 correct date filter function in filtered diagram
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Pages/Charts.razor
  AcademicTimePlanner/Pages/Charts.razor.cs
Labels: enhancement, frontend, refactoring

#63 Fix Github actions for unit test.
  .github/workflows/tests.yml
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
Labels: bug, backend

#67 Update ChartData.cs
  AcademicTimePlanner/Data/ChartData.cs
Labels: bug

#68 Frontend/jansluk/64 create clear button for plan projects loading
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Shared/Wrapper.razor
  AcademicTimePlanner/Store/State/Charts/ChartsState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
Labels: enhancement, frontend

#71 Refactoring/ferbemar/refactring of line graph
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
Labels: refactoring

#75 Frontend/jansluk/64 create clear button for plan projects loading
  AcademicTimePlanner/Data/TogglLoadOverviewData.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
Labels: enhancement, frontend

#74 Refactoring/ferbemar/72 refactor mapping design
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/JSON_Files/PlanProject.json
  AcademicTimePlanner/AcademicTimePlanner.csproj
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
Labels: backend, refactoring

#78 Refactor/ferbemar/bring json in right order for human readability
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
Labels: backend, refactoring

#83 Documentation/jansluk/56 update doc
  doc/doc.bib
  doc/img/ProjectOverview.PNG
  doc/img/ProjectOverview_FinishedProject.png
  doc/img/TimeOverview.PNG
  doc/img/TotalOverview.PNG
  doc/img/TotalOverview_FinishedProject.png
  doc/parts/fundamentals.tex
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation

#80 Documentation/ferbemar/55 describe pair programming in methods
  doc/doc.bib
  doc/parts/methods.tex
Labels: documentation

#82 Backend/jansluk/79 refactoring toggl data logic
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Data/TogglSettings.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
  AcademicTimePlanner/Store/State/Charts/DateFilter.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/SaveTogglSettingsAction.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglSettings.cs
Labels: backend, refactoring

#84 Test/ferbemar/57 write unit tests for synchronization
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
Labels: help wanted, backend

#93 Add test for shifted Toggl entry sums
  AcademicTimePlanner.Tests/DataManagerTest.cs
Labels: backend

#96 Frontend/ferbemar/87 add functionality to create plan projects
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Store/State/ProjectFiles/AddRepetitionEntryAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/AddSingleEntryAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/CreatePlanTaskAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/FinishPlanProjectCreationAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SwitchCreationStepAction.cs
Labels: enhancement, frontend

#100 Frontend/jansluk/86 add functionality to export plan projects
  AcademicTimePlanner/Data/PlanProjectDownloader.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Store/State/ProjectFiles/DownloadPlanProjectAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/GetPlanProjectForDownloadAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/wwwroot/index.html
Labels: enhancement, frontend

#102 Replace System.Text.Json by Newtonsoft.Json in TogglApiService
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/JSON_Files/TogglData.json
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/Services/TogglApiService/TogglApiService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglDetailResponse.cs
  AcademicTimePlanner/Services/TogglApiService/TogglDetailResponseData.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
Labels: backend, refactoring

#101 Backend/ferbemar/97 add budget functionality
  AcademicTimePlanner.Tests/DataManagerTest.cs
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner/Data/ChartData.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/Pages/Charts.razor.cs
Labels: enhancement, frontend, backend

#105 Update Index.razor.cs
  AcademicTimePlanner/Pages/Index.razor.cs
Labels: bug, frontend

#106 Create LICENSE
  LICENSE
Labels: documentation

#107 Translate UI into englisch
  AcademicTimePlanner/Pages/Charts.razor
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Toggl.razor
Labels: frontend, refactoring

#108 Refactoring/ferbemar/91 prettify application
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/PlanGraph.razor
  AcademicTimePlanner/Pages/PlanGraph.razor.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Shared/NavMenu.razor
  AcademicTimePlanner/Shared/Wrapper.razor
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
Labels: frontend, refactoring

#109 Bugfix/jansluk/104 remove charts page error if no projects loaded
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Toggl.razor
Labels: bug, frontend

#110 Swap names of charts and index
  AcademicTimePlanner/Pages/Charts.razor
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Pages/PlanProjects.razor
  AcademicTimePlanner/Pages/PlanProjects.razor.cs
  AcademicTimePlanner/Shared/NavMenu.razor
Labels: frontend, refactoring
