Repository DuplosFidibuss/academic-time-planner, pull requests merged in 2022-10, with the labels that each got.

#13 Documentation/jansluk/fundamentals prototype
  doc/doc.bib
  doc/doc.tex
  doc/img/figure1_prototype_charts.png
  doc/parts/theoretische_grundlagen.tex
Labels: documentation

#14 Documentation/jansluk/fundamentals toggl
  doc/doc.bib
  doc/parts/theoretische_grundlagen.tex
Labels: documentation

#17 first draft Organization Methodology
  doc/doc.bib
  doc/parts/vorgehen_methoden.tex
Labels: documentation

#18 first draft github
  doc/doc.bib
  doc/parts/theoretische_grundlagen.tex
Labels: documentation

#15 Documentation/jansluk/methods proof of approach
  doc/doc.tex
  doc/parts/vorgehen_methoden.tex
Labels: documentation

#19 Documentation/jansluk/methods git
  doc/doc.bib
  doc/parts/theoretische_grundlagen.tex
  doc/parts/vorgehen_methoden.tex
Labels: documentation

#20 Documentation/ferbemar/3 describe fundamentals mapping concept
  doc/doc.bib
  doc/doc.tex
  doc/img/classdiagram_prototype.PNG
  doc/img/entitydiagram_prototype.PNG
  doc/parts/discussion_prospects.tex
  doc/parts/fundamentals.tex
  doc/parts/introduction.tex
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation

#34 Documentation/jansluk/30 cleanup current documentation
  doc/parts/fundamentals.tex
  doc/parts/introduction.tex
  doc/parts/methods.tex
Labels: documentation

#33 Backend/ferbemar/21 implement mapping concept
  AcademicTimePlanner/AcademicTimePlanner.csproj
  AcademicTimePlanner/DataMapping/Budget/Budget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProjectBudget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Plan/TimeSpan.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
Labels: enhancement, backend

#36 Feature/jansluk/31 data manager
  AcademicTimePlanner.Tests/TogglServiceTests.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Pages/Toggl.razor
  AcademicTimePlanner/Pages/Toggl.razor.cs
  AcademicTimePlanner/Program.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Services/TogglApiService/ITogglApiService.cs
  AcademicTimePlanner/Services/TogglApiService/TogglDetailResponseData.cs
  AcademicTimePlanner/Services/TogglService/ITogglService.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
  AcademicTimePlanner/Store/State/Toggl/Reducers.cs
  AcademicTimePlanner/Store/State/Toggl/SetTogglDataAction.cs
  AcademicTimePlanner/Store/State/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/Store/State/Toggl/TogglState.cs
Labels: enhancement, backend

#35 First draft JSON documentation.
  .gitignore
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner.Tests/JSON_Files/PlanProject.json
  AcademicTimePlanner/AcademicTimePlanner.csproj
  AcademicTimePlanner/DataMapping/Budget/Budget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProjectBudget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Plan/TimeSpan.cs
  AcademicTimePlanner/JSONHandling/importExportJSON.cs
  doc/doc.bib
  doc/img/JSONExample.PNG
  doc/parts/fundamentals.tex
Labels: documentation

#37 Update .gitignore
  .gitignore
Labels: bug, backend

#38 Refactoring get and set
  AcademicTimePlanner/DataMapping/Budget/Budget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProjectBudget.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Plan/TimeSpan.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
Labels: backend, refactoring

#40 Documentation/jansluk/mapping concept and chart display research
  doc/doc.bib
  doc/img/blazorise-charts.png
  doc/img/plotly-charts.png
  doc/img/radzen-charts.png
  doc/parts/fundamentals.tex
  doc/parts/methods.tex
Labels: documentation

#39 Feature/jansluk/24 load test plan project
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner/AcademicTimePlanner.csproj
  AcademicTimePlanner/Pages/Index.razor
  AcademicTimePlanner/Pages/Index.razor.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Effects.cs
  AcademicTimePlanner/Store/State/ProjectFiles/LoadPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/ProjectFiles/ProjectFilesState.cs
  AcademicTimePlanner/Store/State/ProjectFiles/Reducers.cs
  AcademicTimePlanner/Store/State/ProjectFiles/SetPlanProjectsAction.cs
  AcademicTimePlanner/Store/State/Toggl/Effects.cs
Labels: enhancement, frontend, backend

#41 Update DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
Labels: bug, backend

#42 Test/jansluk/25 research chart display possbilities plotly.blazor
  AcademicTimePlanner/AcademicTimePlanner.csproj
  AcademicTimePlanner/JSONHandling/JsonFileHandler.cs
  AcademicTimePlanner/Pages/Charts.razor
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Pages/PlanGraph.razor
  AcademicTimePlanner/Shared/Chart.razor
  AcademicTimePlanner/Shared/Chart.razor.cs
  AcademicTimePlanner/Shared/Chart.razor.css
  AcademicTimePlanner/_Imports.razor
  AcademicTimePlanner/wwwroot/index.html
  AcademicTimePlanner/wwwroot/scripts/genericChart.js
Labels: frontend

#46 Feature/jansluk/44 chart data transfer object
  AcademicTimePlanner/Data/ChartData.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Services/DataManagerService/DataManagerService.cs
  AcademicTimePlanner/Services/DataManagerService/IDataManagerService.cs
Labels: enhancement, backend

#47 Backend/ferbemar/43 create test toggl project
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglEntrySum.cs
Labels: backend

#48 changed int to double
  AcademicTimePlanner.Tests/JSONHandlingTest.cs
  AcademicTimePlanner/Data/ChartData.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntry.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Services/TogglService/TogglService.cs
Labels: bug, backend

#50 Frontend/ferbemar/26 implement first draft of displaying graphical time difference
  AcademicTimePlanner/Data/ChartData.cs
  AcademicTimePlanner/Data/DataManager.cs
  AcademicTimePlanner/Data/DateFilter.cs
  AcademicTimePlanner/Data/TestTogglProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanEntryRepetition.cs
  AcademicTimePlanner/DataMapping/Plan/PlanProject.cs
  AcademicTimePlanner/DataMapping/Plan/PlanTask.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglProject.cs
  AcademicTimePlanner/DataMapping/Toggl/TogglTask.cs
  AcademicTimePlanner/Pages/Charts.razor
  AcademicTimePlanner/Pages/Charts.razor.cs
  AcademicTimePlanner/Shared/Filter.razor
  AcademicTimePlanner/Shared/Filter.razor.cs
  AcademicTimePlanner/Shared/NavMenu.razor
  AcademicTimePlanner/Store/State/Charts/ChangeFilterAction.cs
  AcademicTimePlanner/Store/State/Charts/ChartsState.cs
  AcademicTimePlanner/Store/State/Charts/Effects.cs
  AcademicTimePlanner/Store/State/Charts/FetchChartDataAction.cs
  AcademicTimePlanner/Store/State/Charts/FilterChartDataAction.cs
  AcademicTimePlanner/Store/State/Charts/Reducers.cs
  AcademicTimePlanner/Store/State/Charts/SetChartDataAction.cs
  AcademicTimePlanner/wwwroot/index.html
  AcademicTimePlanner/wwwroot/scripts/filter.js
Labels: enhancement, frontend

#53 Documentation/ferbemar/result of graphes
  doc/img/ProjectOverview.PNG
  doc/img/TimeOverview.PNG
  doc/img/TotalOverview.PNG
  doc/parts/methods.tex
  doc/parts/results.tex
Labels: documentation
